// check if the image is AI generated or not
import Head from 'next/head'
import styles from '@/styles/Home.module.css'
import { useState, useEffect } from 'react'

export default function WhichFont() {
  const [font, setFont] = useState(null);
  const detectFont = async (event) => {
    const file = event.target.files[0];
    const canvas = document.getElementById('canvas');
    const ctx = canvas.getContext('2d');
    const img = new Image();
    img.onload = () => {
      canvas.width = img.width;
      canvas.height = img.height;
      ctx.drawImage(img, 0, 0);
      setFont(null);
    }
    img.src = URL.createObjectURL(file);
  }

  const getFont = async () => {
    // get canvas as data url send to gpt as req body
    const canvas = document.getElementById('canvas');
    // reduce the size of the image to 500x500
    let tempCanvas = document.createElement('canvas');
    let tempCtx = tempCanvas.getContext('2d');
    tempCanvas.width = 500;
    tempCanvas.height = 500;
    tempCtx.drawImage(canvas, 0, 0, 500, 500);
    const dataURL = tempCanvas.toDataURL();
    setFont('Checking...');
    const response = await fetch('/api/gpt', {
      method: 'POST',
      body: JSON.stringify({
        prompt: "please analyze the attached image and determine if it was ai generated or not, to give you an example of the state of current ai I have attached ai images (after current image) that were generated by a computer, please analyze the image and determine if it was ai generated or not. Respond only with 'yes' or 'no', if you are unsure please respond with 'unsure'.",
        image_url: dataURL,
        image_urls: ['https://cdn.dribbble.com/userupload/10508184/file/original-d74b8f97c1af7feef77e4ac0635907c4.png?resize=752x501', 'https://mir-s3-cdn-cf.behance.net/project_modules/hd/e7fafc163059593.63dff39c3b13d.png'],
        model: 'gpt-4o'
      }),
    });
    const data = await response.json();
    setFont(data.response.includes('yes') ? 'AI' : data.response.includes('unsure') ? 'Unsure' : 'Not AI');
  }

  useEffect(() => {
    // when pasting image add it to canvas
    window.addEventListener('paste', async (event) => {
      const items = (event.clipboardData || event.originalEvent.clipboardData).items;
      for (const item of items) {
        if (item.kind === 'file') {
          const blob = item.getAsFile();
          const reader = new FileReader();
          reader.onload = (event) => {
            const canvas = document.getElementById('canvas');
            const ctx = canvas.getContext('2d');
            const img = new Image();
            img.onload = () => {
              canvas.width = img.width;
              canvas.height = img.height;
              ctx.drawImage(img, 0, 0);
              setFont(null);
            }
            img.src = event.target.result;
          }
          reader.readAsDataURL(blob);
        }
      }
    });
  }, [])

  
  return (
    <>
      <Head>
        <title>AI or not</title>
        <meta name="description" content="Check if the image is AI generated or not" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      {/* input to upload, canvas to render and prompt to detect the font */}
      <main>
        <h1 className={styles.title}>AI or not</h1>
        <h2 className={styles.description}>
          Check if the image is AI generated or not
        </h2>
        <canvas id="canvas"
          width={500}
          height={500}
          style={{
            border: '1px solid #333',
            borderRadius: '5px',
            width: '100%',
            height: 'auto'

          }}
        ></canvas>
        <input type="file" accept="image/*" onChange={detectFont} />
        <button onClick={getFont} style={{ marginTop: 20}}>Get</button>
        <span style={{
          fontSize: '2rem',
          padding: '1rem',
          display: 'block',
          textAlign: 'left',
          whiteSpace: 'pre-wrap',
          marginTop: '1rem',
          fontWeight: 'bold'
        }}>
          {font ? `${font.toUpperCase()}` : ''}
        </span>

      </main>
    </>
  )

}