// Extract terms from a list of sentences using descending n-gram cover
import Head from 'next/head'
import styles from '@/styles/Home.module.css'
import { useState, useEffect } from 'react'

// Default stopwords
const defaultStopwords =[
    "about",
    "above",
    "after",
    "again",
    "against",
    "all",
    "am",
    "an",
    "and",
    "any",
    "are",
    "aren't",
    "as",
    "at",
    "be",
    "because",
    "been",
    "before",
    "being",
    "below",
    "between",
    "both",
    "but",
    "by",
    "can't",
    "cannot",
    "could",
    "couldn't",
    "did",
    "didn't",
    "do",
    "does",
    "doesn't",
    "doing",
    "don't",
    "down",
    "during",
    "each",
    "few",
    "for",
    "from",
    "further",
    "had",
    "hadn't",
    "has",
    "hasn't",
    "have",
    "haven't",
    "having",
    "he",
    "he'd",
    "he'll",
    "he's",
    "her",
    "here",
    "here's",
    "hers",
    "herself",
    "him",
    "himself",
    "his",
    "how",
    "how's",
    "i",
    "i'd",
    "i'll",
    "i'm",
    "i've",
    "if",
    "in",
    "into",
    "is",
    "isn't",
    "it",
    "it's",
    "its",
    "itself",
    "let's",
    "me",
    "more",
    "most",
    "mustn't",
    "my",
    "myself",
    "no",
    "nor",
    "not",
    "of",
    "off",
    "on",
    "once",
    "only",
    "or",
    "other",
    "ought",
    "our",
    "ours",
    "ourselves",
    "out",
    "over",
    "own",
    "same",
    "shan't",
    "she",
    "she'd",
    "she'll",
    "she's",
    "should",
    "shouldn't",
    "so",
    "some",
    "such",
    "than",
    "that",
    "that's",
    "the",
    "their",
    "theirs",
    "them",
    "themselves",
    "then",
    "there",
    "there's",
    "these",
    "they",
    "they'd",
    "they'll",
    "they're",
    "they've",
    "this",
    "those",
    "through",
    "to",
    "too",
    "under",
    "until",
    "up",
    "very",
    "was",
    "wasn't",
    "we",
    "we'd",
    "we'll",
    "we're",
    "we've",
    "were",
    "weren't",
    "what",
    "what's",
    "when",
    "when's",
    "where",
    "where's",
    "which",
    "while",
    "who",
    "who's",
    "whom",
    "why",
    "why's",
    "with",
    "won't",
    "would",
    "wouldn't",
    "you",
    "you'd",
    "you'll",
    "you're",
    "you've",
    "your",
    "yours",
    "yourself",
    "yourselves",
    "able",
    "abst",
    "accordance",
    "according",
    "accordingly",
    "across",
    "act",
    "actually",
    "added",
    "adj",
    "affected",
    "affecting",
    "affects",
    "afterwards",
    "ah",
    "almost",
    "alone",
    "along",
    "already",
    "also",
    "although",
    "always",
    "among",
    "amongst",
    "announce",
    "another",
    "anybody",
    "anyhow",
    "anymore",
    "anyone",
    "anything",
    "anyway",
    "anyways",
    "anywhere",
    "apparently",
    "approximately",
    "aren",
    "arent",
    "arise",
    "around",
    "aside",
    "ask",
    "asking",
    "auth",
    "available",
    "away",
    "awfully",
    "b",
    "back",
    "became",
    "become",
    "becomes",
    "becoming",
    "beforehand",
    "begin",
    "beginning",
    "beginnings",
    "begins",
    "behind",
    "believe",
    "beside",
    "besides",
    "beyond",
    "biol",
    "brief",
    "briefly",
    "c",
    "ca",
    "came",
    "can",
    "cause",
    "causes",
    "certain",
    "certainly",
    "co",
    "com",
    "come",
    "comes",
    "contain",
    "containing",
    "contains",
    "couldnt",
    "d",
    "date",
    "different",
    "done",
    "downwards",
    "due",
    "e",
    "ed",
    "edu",
    "effect",
    "eg",
    "eight",
    "eighty",
    "either",
    "else",
    "elsewhere",
    "end",
    "ending",
    "enough",
    "especially",
    "et",
    "et-al",
    "etc",
    "even",
    "ever",
    "every",
    "everybody",
    "everyone",
    "everything",
    "everywhere",
    "ex",
    "except",
    "f",
    "far",
    "ff",
    "fifth",
    "first",
    "five",
    "fix",
    "followed",
    "following",
    "follows",
    "former",
    "formerly",
    "forth",
    "found",
    "four",
    "furthermore",
    "g",
    "gave",
    "get",
    "gets",
    "getting",
    "give",
    "given",
    "gives",
    "giving",
    "go",
    "goes",
    "gone",
    "got",
    "gotten",
    "h",
    "happens",
    "hardly",
    "hed",
    "hence",
    "hereafter",
    "hereby",
    "herein",
    "heres",
    "hereupon",
    "hes",
    "hi",
    "hid",
    "hither",
    "home",
    "howbeit",
    "however",
    "hundred",
    "id",
    "ie",
    "im",
    "immediate",
    "immediately",
    "importance",
    "important",
    "inc",
    "indeed",
    "index",
    "information",
    "instead",
    "invention",
    "inward",
    "itd",
    "it'll",
    "j",
    "just",
    "k",
    "keep",
    "keeps",
    "kept",
    "kg",
    "km",
    "know",
    "known",
    "knows",
    "l",
    "largely",
    "last",
    "lately",
    "later",
    "latter",
    "latterly",
    "least",
    "less",
    "lest",
    "let",
    "lets",
    "like",
    "liked",
    "likely",
    "line",
    "little",
    "'ll",
    "look",
    "looking",
    "looks",
    "ltd",
    "m",
    "made",
    "mainly",
    "make",
    "makes",
    "many",
    "may",
    "maybe",
    "mean",
    "means",
    "meantime",
    "meanwhile",
    "merely",
    "mg",
    "might",
    "million",
    "miss",
    "ml",
    "moreover",
    "mostly",
    "mr",
    "mrs",
    "much",
    "mug",
    "must",
    "n",
    "na",
    "name",
    "namely",
    "nay",
    "nd",
    "near",
    "nearly",
    "necessarily",
    "necessary",
    "need",
    "needs",
    "neither",
    "never",
    "nevertheless",
    "new",
    "next",
    "nine",
    "ninety",
    "nobody",
    "non",
    "none",
    "nonetheless",
    "noone",
    "normally",
    "nos",
    "noted",
    "nothing",
    "now",
    "nowhere",
    "o",
    "obtain",
    "obtained",
    "obviously",
    "often",
    "oh",
    "ok",
    "okay",
    "old",
    "omitted",
    "one",
    "ones",
    "onto",
    "ord",
    "others",
    "otherwise",
    "outside",
    "overall",
    "owing",
    "p",
    "page",
    "pages",
    "part",
    "particular",
    "particularly",
    "past",
    "per",
    "perhaps",
    "placed",
    "please",
    "plus",
    "poorly",
    "possible",
    "possibly",
    "potentially",
    "pp",
    "predominantly",
    "present",
    "previously",
    "primarily",
    "probably",
    "promptly",
    "proud",
    "provides",
    "put",
    "q",
    "que",
    "quickly",
    "quite",
    "qv",
    "r",
    "ran",
    "rather",
    "rd",
    "re",
    "readily",
    "really",
    "recent",
    "recently",
    "ref",
    "refs",
    "regarding",
    "regardless",
    "regards",
    "related",
    "relatively",
    "research",
    "respectively",
    "resulted",
    "resulting",
    "results",
    "right",
    "run",
    "s",
    "said",
    "saw",
    "say",
    "saying",
    "says",
    "sec",
    "section",
    "see",
    "seeing",
    "seem",
    "seemed",
    "seeming",
    "seems",
    "seen",
    "self",
    "selves",
    "sent",
    "seven",
    "several",
    "shall",
    "shed",
    "shes",
    "show",
    "showed",
    "shown",
    "showns",
    "shows",
    "significant",
    "significantly",
    "similar",
    "similarly",
    "since",
    "six",
    "slightly",
    "somebody",
    "somehow",
    "someone",
    "somethan",
    "something",
    "sometime",
    "sometimes",
    "somewhat",
    "somewhere",
    "soon",
    "sorry",
    "specifically",
    "specified",
    "specify",
    "specifying",
    "still",
    "stop",
    "strongly",
    "sub",
    "substantially",
    "successfully",
    "sufficiently",
    "suggest",
    "sup",
    "sure",
    "t",
    "take",
    "taken",
    "taking",
    "tell",
    "tends",
    "th",
    "thank",
    "thanks",
    "thanx",
    "that'll",
    "thats",
    "that've",
    "thence",
    "thereafter",
    "thereby",
    "thered",
    "therefore",
    "therein",
    "there'll",
    "thereof",
    "therere",
    "theres",
    "thereto",
    "thereupon",
    "there've",
    "theyd",
    "theyre",
    "think",
    "thou",
    "though",
    "thoughh",
    "thousand",
    "throug",
    "throughout",
    "thru",
    "thus",
    "til",
    "tip",
    "together",
    "took",
    "toward",
    "towards",
    "tried",
    "tries",
    "truly",
    "try",
    "trying",
    "ts",
    "twice",
    "two",
    "u",
    "un",
    "unfortunately",
    "unless",
    "unlike",
    "unlikely",
    "unto",
    "upon",
    "ups",
    "us",
    "use",
    "used",
    "useful",
    "usefully",
    "usefulness",
    "uses",
    "using",
    "usually",
    "v",
    "value",
    "various",
    "'ve",
    "via",
    "viz",
    "vol",
    "vols",
    "vs",
    "w",
    "want",
    "wants",
    "wasnt",
    "way",
    "wed",
    "welcome",
    "went",
    "werent",
    "whatever",
    "what'll",
    "whats",
    "whence",
    "whenever",
    "whereafter",
    "whereas",
    "whereby",
    "wherein",
    "wheres",
    "whereupon",
    "wherever",
    "whether",
    "whim",
    "whither",
    "whod",
    "whoever",
    "whole",
    "who'll",
    "whomever",
    "whos",
    "whose",
    "widely",
    "willing",
    "wish",
    "within",
    "without",
    "wont",
    "words",
    "world",
    "wouldnt",
    "www",
    "x",
    "y",
    "yes",
    "yet",
    "youd",
    "youre",
    "z",
    "zero",
    "'tis",
    "'twas",
    "10",
    "39",
    "a's",
    "ableabout",
    "abroad",
    "ad",
    "adopted",
    "ae",
    "af",
    "ag",
    "ago",
    "ahead",
    "ai",
    "ain't",
    "aint",
    "al",
    "allow",
    "allows",
    "alongside",
    "amid",
    "amidst",
    "amoungst",
    "amount",
    "ao",
    "apart",
    "appear",
    "appreciate",
    "appropriate",
    "aq",
    "ar",
    "area",
    "areas",
    "arpa",
    "asked",
    "asks",
    "associated",
    "au",
    "aw",
    "az",
    "ba",
    "backed",
    "backing",
    "backs",
    "backward",
    "backwards",
    "bb",
    "bd",
    "began",
    "beings",
    "best",
    "better",
    "bf",
    "bg",
    "bh",
    "bi",
    "big",
    "bill",
    "billion",
    "bj",
    "bm",
    "bn",
    "bo",
    "bottom",
    "br",
    "bs",
    "bt",
    "buy",
    "bv",
    "bw",
    "bz",
    "c'mon",
    "c's",
    "call",
    "cant",
    "caption",
    "case",
    "cases",
    "cc",
    "cd",
    "cf",
    "cg",
    "ch",
    "changes",
    "ci",
    "ck",
    "cl",
    "clear",
    "clearly",
    "click",
    "cm",
    "cmon",
    "cn",
    "co.",
    "computer",
    "con",
    "concerning",
    "consequently",
    "consider",
    "considering",
    "copy",
    "corresponding",
    "could've",
    "couldn",
    "course",
    "cr",
    "cry",
    "cs",
    "cu",
    "currently",
    "cv",
    "cx",
    "cy",
    "cz",
    "dare",
    "daren't",
    "darent",
    "de",
    "dear",
    "definitely",
    "describe",
    "described",
    "despite",
    "detail",
    "didn",
    "didnt",
    "differ",
    "differently",
    "directly",
    "dj",
    "dk",
    "dm",
    "doesn",
    "doesnt",
    "don",
    "dont",
    "doubtful",
    "downed",
    "downing",
    "downs",
    "dz",
    "early",
    "ec",
    "ee",
    "eh",
    "eleven",
    "empty",
    "ended",
    "ends",
    "entirely",
    "er",
    "es",
    "evenly",
    "evermore",
    "exactly",
    "example",
    "face",
    "faces",
    "fact",
    "facts",
    "fairly",
    "farther",
    "felt",
    "fewer",
    "fi",
    "fifteen",
    "fifty",
    "fify",
    "fill",
    "find",
    "finds",
    "fire",
    "fj",
    "fk",
    "fm",
    "fo",
    "forever",
    "forty",
    "forward",
    "fr",
    "free",
    "front",
    "full",
    "fully",
    "furthered",
    "furthering",
    "furthers",
    "fx",
    "ga",
    "gb",
    "gd",
    "ge",
    "general",
    "generally",
    "gf",
    "gg",
    "gh",
    "gi",
    "gl",
    "gm",
    "gmt",
    "gn",
    "going",
    "good",
    "goods",
    "gov",
    "gp",
    "gq",
    "gr",
    "great",
    "greater",
    "greatest",
    "greetings",
    "group",
    "grouped",
    "grouping",
    "groups",
    "gs",
    "gt",
    "gu",
    "gw",
    "gy",
    "hadnt",
    "half",
    "hasn",
    "hasnt",
    "haven",
    "havent",
    "hell",
    "hello",
    "help",
    "herse”",
    "high",
    "higher",
    "highest",
    "himse”",
    "hk",
    "hm",
    "hn",
    "homepage",
    "hopefully",
    "how'd",
    "how'll",
    "hr",
    "ht",
    "htm",
    "html",
    "http",
    "hu",
    "i.e.",
    "ignored",
    "ii",
    "il",
    "ill",
    "inasmuch",
    "inc.",
    "indicate",
    "indicated",
    "indicates",
    "inner",
    "inside",
    "insofar",
    "int",
    "interest",
    "interested",
    "interesting",
    "interests",
    "io",
    "iq",
    "ir",
    "isn",
    "isnt",
    "it'd",
    "itll",
    "itse”",
    "ive",
    "je",
    "jm",
    "jo",
    "join",
    "jp",
    "ke",
    "keys",
    "kh",
    "ki",
    "kind",
    "kn",
    "knew",
    "kp",
    "kr",
    "kw",
    "ky",
    "kz",
    "la",
    "large",
    "latest",
    "lb",
    "lc",
    "length",
    "li",
    "likewise",
    "lk",
    "ll",
    "long",
    "longer",
    "longest",
    "low",
    "lower",
    "lr",
    "ls",
    "lt",
    "lu",
    "lv",
    "ly",
    "ma",
    "making",
    "man",
    "mayn't",
    "maynt",
    "mc",
    "md",
    "member",
    "members",
    "men",
    "mh",
    "microsoft",
    "might've",
    "mightn't",
    "mightnt",
    "mil",
    "mill",
    "mine",
    "minus",
    "mk",
    "mm",
    "mn",
    "mo",
    "move",
    "mp",
    "mq",
    "ms",
    "msie",
    "mt",
    "mu",
    "must've",
    "mustnt",
    "mv",
    "mw",
    "mx",
    "myse”",
    "mz",
    "nc",
    "ne",
    "needed",
    "needing",
    "needn't",
    "neednt",
    "net",
    "netscape",
    "neverf",
    "neverless",
    "newer",
    "newest",
    "nf",
    "ng",
    "ni",
    "nl",
    "no-one",
    "notwithstanding",
    "novel",
    "np",
    "nr",
    "nu",
    "null",
    "number",
    "numbers",
    "nz",
    "older",
    "oldest",
    "om",
    "one's",
    "open",
    "opened",
    "opening",
    "opens",
    "opposite",
    "order",
    "ordered",
    "ordering",
    "orders",
    "org",
    "oughtn't",
    "oughtnt",
    "pa",
    "parted",
    "parting",
    "parts",
    "pe",
    "pf",
    "pg",
    "ph",
    "pk",
    "pl",
    "place",
    "places",
    "pm",
    "pmid",
    "pn",
    "point",
    "pointed",
    "pointing",
    "points",
    "pr",
    "presented",
    "presenting",
    "presents",
    "presumably",
    "problem",
    "problems",
    "provided",
    "pt",
    "puts",
    "pw",
    "py",
    "qa",
    "reasonably",
    "reserved",
    "ring",
    "ro",
    "room",
    "rooms",
    "round",
    "ru",
    "rw",
    "sa",
    "sb",
    "sc",
    "sd",
    "se",
    "second",
    "secondly",
    "seconds",
    "sees",
    "sensible",
    "serious",
    "seriously",
    "seventy",
    "sg",
    "sh",
    "shant",
    "shell",
    "should've",
    "shouldn",
    "shouldnt",
    "showing",
    "si",
    "side",
    "sides",
    "sincere",
    "site",
    "sixty",
    "sj",
    "sk",
    "sl",
    "sm",
    "small",
    "smaller",
    "smallest",
    "sn",
    "someday",
    "sr",
    "st",
    "state",
    "states",
    "su",
    "sv",
    "sy",
    "system",
    "sz",
    "t's",
    "tc",
    "td",
    "ten",
    "test",
    "text",
    "tf",
    "tg",
    "thatll",
    "thatve",
    "there'd",
    "there're",
    "therell",
    "thereve",
    "theyll",
    "theyve",
    "thick",
    "thin",
    "thing",
    "things",
    "thinks",
    "third",
    "thirty",
    "thorough",
    "thoroughly",
    "thought",
    "thoughts",
    "three",
    "till",
    "tis",
    "tj",
    "tk",
    "tm",
    "tn",
    "today",
    "top",
    "tp",
    "tr",
    "trillion",
    "tt",
    "turn",
    "turned",
    "turning",
    "turns",
    "tv",
    "tw",
    "twas",
    "twelve",
    "twenty",
    "tz",
    "ua",
    "ug",
    "uk",
    "um",
    "underneath",
    "undoing",
    "upwards",
    "uucp",
    "uy",
    "uz",
    "va",
    "vc",
    "ve",
    "versus",
    "vg",
    "vi",
    "vn",
    "vu",
    "wanted",
    "wanting",
    "wasn",
    "ways",
    "web",
    "webpage",
    "website",
    "well",
    "wells",
    "weren",
    "weve",
    "wf",
    "what'd",
    "what've",
    "whatll",
    "whatve",
    "when'd",
    "when'll",
    "where'd",
    "where'll",
    "whichever",
    "whilst",
    "who'd",
    "wholl",
    "why'd",
    "why'll",
    "width",
    "will",
    "won",
    "wonder",
    "work",
    "worked",
    "working",
    "works",
    "would've",
    "wouldn",
    "ws",
    "ye",
    "year",
    "years",
    "youll",
    "young",
    "younger",
    "youngest",
    "youve",
    "yt",
    "yu",
    "za",
    "zm",
    "zr",
    "I",
    "herse",
    "himse",
    "yond",
    "yonder",
    "yon",
    "zillion",
    "umpteen",
    "username",
    "uponed",
    "upons",
    "uponing",
    "upping",
    "upped",
    "unliker",
    "unlikest",
    "usedest",
    "rath",
    "rathest",
    "rathe",
    "relate",
    "res",
    "respecting",
    "qua",
    "neaths",
    "neath",
    "nethe",
    "nethermost",
    "necessariest",
    "necessarier",
    "nigh",
    "nighest",
    "nigher",
    "nobodies",
    "nowheres",
    "noes",
    "nothings",
    "nathless",
    "natheless",
    "tills",
    "tilled",
    "tilling",
    "towardest",
    "towarder",
    "thy",
    "thyself",
    "thous",
    "thouses",
    "thoroughest",
    "thorougher",
    "thruer",
    "thruest",
    "thro",
    "throughest",
    "througher",
    "thine",
    "thises",
    "thee",
    "thenest",
    "thener",
    "therer",
    "therest",
    "owt",
    "owning",
    "owned",
    "owns",
    "otherwisest",
    "otherwiser",
    "oftener",
    "oftenest",
    "offs",
    "offest",
    "oughts",
    "ourself",
    "outest",
    "outed",
    "outwith",
    "outs",
    "overallest",
    "overaller",
    "overalls",
    "overs",
    "orer",
    "orest",
    "oneself",
    "onest",
    "ons",
    "atween",
    "athwart",
    "atop",
    "afore",
    "afterward",
    "afterest",
    "afterer",
    "ain",
    "anent",
    "anear",
    "andor",
    "ares",
    "aest",
    "aer",
    "abaft",
    "abafter",
    "abaftest",
    "abovest",
    "abover",
    "abouter",
    "aboutest",
    "aid",
    "apartest",
    "aparter",
    "appeared",
    "appears",
    "appearing",
    "appropriating",
    "appropriatest",
    "appropriates",
    "appropriater",
    "appropriated",
    "allest",
    "aller",
    "allyou",
    "alls",
    "albeit",
    "asides",
    "aslant",
    "ases",
    "astrider",
    "astride",
    "astridest",
    "astraddlest",
    "astraddler",
    "astraddle",
    "availablest",
    "availabler",
    "aughts",
    "aught",
    "variousest",
    "variouser",
    "vis-a-vis",
    "vis-a-viser",
    "vis-a-visest",
    "veriest",
    "verier",
    "gotta",
    "byandby",
    "by-and-by",
    "bist",
    "buts",
    "becomings",
    "becominger",
    "becomingest",
    "behinds",
    "beforehandest",
    "beforehander",
    "bettered",
    "betters",
    "bettering",
    "betwixt",
    "beneath",
    "mucher",
    "muchest",
    "musts",
    "musths",
    "musth",
    "main",
    "mayest",
    "mauger",
    "maugre",
    "meanwhiles",
    "mights",
    "midst",
    "midsts",
    "huh",
    "humph",
    "hereafters",
    "hadst",
    "haves",
    "hast",
    "hae",
    "hath",
    "hitherest",
    "hitherer",
    "how-do-you-do",
    "howdoyoudo",
    "hoos",
    "hoo",
    "woulded",
    "woulding",
    "woulds",
    "wast",
    "wert",
    "withal",
    "whateverer",
    "whateverest",
    "whatsoeverer",
    "whatsoeverest",
    "whatsoever",
    "whencesoever",
    "whensoever",
    "whenas",
    "wheen",
    "whereto",
    "whereon",
    "whereof",
    "wherewithal",
    "wherewith",
    "whereinto",
    "wheresoever",
    "wherefrom",
    "whichsoever",
    "whiles",
    "whithersoever",
    "whosoever",
    "whoso",
    "syne",
    "syn",
    "shalling",
    "shalled",
    "shalls",
    "shoulding",
    "shoulded",
    "shoulds",
    "sayyid",
    "sayid",
    "saider",
    "saidest",
    "samest",
    "sames",
    "samer",
    "saved",
    "sans",
    "sanses",
    "sanserifs",
    "sanserif",
    "soer",
    "soest",
    "sobeit",
    "sometimest",
    "sometimer",
    "severaler",
    "severalest",
    "seriousest",
    "seriouser",
    "senza",
    "send",
    "seemingest",
    "seeminger",
    "seemings",
    "summat",
    "sups",
    "supping",
    "supped",
    "sine",
    "sines",
    "sith",
    "stopped",
    "plaintiff",
    "plenty",
    "plenties",
    "pleased",
    "pleases",
    "particulars",
    "particularest",
    "particularer",
    "pro",
    "providing",
    "provide",
    "layabout",
    "layabouts",
    "latterest",
    "latterer",
    "latters",
    "lots",
    "lotting",
    "lotted",
    "lot",
    "ifs",
    "info",
    "idem",
    "idemer",
    "idemest",
    "immediatest",
    "immediater",
    "inwards",
    "inwardest",
    "inwarder",
    "indicating",
    "fs",
    "figupon",
    "figupons",
    "figupon…"
]


/**
 * Preprocess a question: lowercase, remove punctuation, tokenize, remove stopwords
 */
function preprocessQuestion(question, removeStopwords = true, stopwordSet = new Set()) {
    const tokens = question
        .toLowerCase()
        .replace(/[^\w\s]/g, ' ')  // Replace punctuation with spaces
        .split(/\s+/)              // Split on whitespace
        .filter(word => word.length > 0);  // Remove empty strings

    if (removeStopwords) {
        return tokens.filter(word => !stopwordSet.has(word));
    }

    return tokens;
}

/**
 * Extract all n-grams of length n from a token array
 */
function extractNgrams(tokens, n) {
    const ngrams = [];
    for (let i = 0; i <= tokens.length - n; i++) {
        const ngram = tokens.slice(i, i + n).join(' ');
        ngrams.push(ngram);
    }
    return ngrams;
}

/**
 * Check if an n-gram should be filtered out based on content quality
 */
function shouldFilterNgram(ngram, minContentWords = 1, stopwordsRemoved = true, stopwordSet = new Set()) {
    const words = ngram.split(' ');

    // If stopwords were already removed, we mainly check for length and quality
    if (stopwordsRemoved) {
        // Filter out very short words or numbers-only n-grams
        if (words.some(word => word.length < 2)) return true;
        if (words.every(word => /^\d+$/.test(word))) return true;

        // Filter out n-grams with too few meaningful words
        if (words.length < minContentWords) return true;

        return false;
    }

    // Original filtering if stopwords weren't removed
    const contentWords = words.filter(word => !stopwordSet.has(word));

    // Filter out if all words are stopwords
    if (contentWords.length === 0) return true;

    // Filter out if too few content words
    if (contentWords.length < minContentWords) return true;

    // Filter out very common question patterns
    const commonPatterns = [
        /^(how|what|when|where|why|which|who)\s+(do|does|did|is|are|was|were|can|could|should|would)/,
        /^(do|does|did|is|are|was|were|can|could|should|would)\s+(you|i|we|they)/,
        /^(i|you|we|they)\s+(am|is|are|was|were|have|has|had|do|does|did)/
    ];

    return commonPatterns.some(pattern => pattern.test(ngram));
}

/**
 * Main descending n-gram coverage algorithm
 */
function descendingNgramCover(sentences, maxN = 10, minSentenceCount = 2, minContentWords = 1, removeStopwords = true, stopwordSet = new Set(), minN = 2) {
    // Preprocess all sentences - remove stopwords by default for cleaner n-grams
    const processedSentences = sentences.map(s => preprocessQuestion(s, removeStopwords, stopwordSet));

    // Track coverage
    const covered = new Set();
    const anchors = [];
    const anchorToCoverage = new Map();

    // Descend from maxN to minN
    for (let n = Math.max(maxN, minN); n >= minN; n--) {
        if (covered.size === sentences.length) {
            break;
        }

        // Build n-gram candidates from uncovered sentences only
        const ngramMap = new Map();

        for (let i = 0; i < processedSentences.length; i++) {
            if (covered.has(i)) continue; // Skip already covered sentences

            const tokens = processedSentences[i];
            if (tokens.length < n) continue; // Skip if sentence too short

            const ngrams = extractNgrams(tokens, n);

            for (const ngram of ngrams) {
                // Apply filters
                if (shouldFilterNgram(ngram, minContentWords, removeStopwords, stopwordSet)) continue;

                if (!ngramMap.has(ngram)) {
                    ngramMap.set(ngram, new Set());
                }
                ngramMap.get(ngram).add(i);
            }
        }

        // Filter by minimum sentence count
        const candidateNgrams = Array.from(ngramMap.entries())
            .filter(([ngram, sentenceSet]) => sentenceSet.size >= minSentenceCount)
            .map(([ngram, sentenceSet]) => ({
                ngram,
                sentenceIndices: Array.from(sentenceSet),
                uncoveredCount: Array.from(sentenceSet).filter(i => !covered.has(i)).length
            }))
            .filter(item => item.uncoveredCount > 0)  // Only consider ngrams that cover uncovered sentences
            .sort((a, b) => b.uncoveredCount - a.uncoveredCount);  // Sort by coverage descending

        // Greedily select the best n-grams at this level
        for (const candidate of candidateNgrams) {
            const uncoveredSentences = candidate.sentenceIndices.filter(i => !covered.has(i));

            if (uncoveredSentences.length === 0) continue;  // No new coverage

            // Add this n-gram as an anchor
            anchors.push({
                ngram: candidate.ngram,
                ngramLength: n,
                sentenceIndices: candidate.sentenceIndices,
                newlyCovered: uncoveredSentences
            });

            anchorToCoverage.set(candidate.ngram, candidate.sentenceIndices);

            // Mark sentences as covered
            uncoveredSentences.forEach(i => covered.add(i));

            // Check if we've covered everything
            if (covered.size === sentences.length) {
                break;
            }
        }

        if (covered.size === sentences.length) break;
    }

    return {
        anchors,
        coverage: anchorToCoverage,
        totalCovered: covered.size,
        totalSentences: sentences.length
    };
}

export default function Home() {
  const [text, setText] = useState('')
  const [summaryJSX, setSummaryJSX] = useState([])
  const [loading, setLoading] = useState(false)
  const [maxN, setMaxN] = useState(3)
  const [separator, setSeparator] = useState('single')
  const [customSeparator, setCustomSeparator] = useState('---')
  const [filterWords, setFilterWords] = useState('')
  const [customStopwords, setCustomStopwords] = useState('')
  const [allowSingleNgram, setAllowSingleNgram] = useState(false)
  const [removeStopwords, setRemoveStopwords] = useState(true)
  const [removeCustomStopwords, setRemoveCustomStopwords] = useState(true)

  const extractTerms = async () => {
    setLoading(true)
    let sep;
    if (separator === 'double') {
      sep = /\n\n+/;
    } else if (separator === 'custom') {
      sep = customSeparator || '\n'; // Default to newline if empty
    } else {
      sep = '\n';
    }
    let questions = text.split(sep).map(line => line.trim()).filter(line => line.length > 0)
    questions = Array.from(new Set(questions)) // Remove duplicates
    console.log(questions);

    // Filter questions based on filter words
    if (filterWords.trim()) {
      const filters = filterWords.split(',').map(w => w.trim().toLowerCase()).filter(w => w.length > 0)
      if (filters.length > 0) {
        questions = questions.filter(q => filters.some(f => q.toLowerCase().includes(f)))
      }
    }

    if (questions.length === 0) {
      setSummaryJSX([<p key="no-data" style={{margin: 0}}>No questions provided or none match the filter.</p>])
      setLoading(false)
      return
    }

    // Create full stopword set including custom ones based on checkboxes
    const customStopwordsArray = customStopwords.split(',').map(w => w.trim().toLowerCase()).filter(w => w.length > 0)
    const fullStopwordSet = new Set()
    if (removeStopwords) {
      defaultStopwords.forEach(w => fullStopwordSet.add(w.toLowerCase()))
    }
    if (removeCustomStopwords) {
      customStopwordsArray.forEach(w => fullStopwordSet.add(w))
    }

    const minN = allowSingleNgram ? 1 : 2
    const result = descendingNgramCover(questions, maxN, 2, 1, removeStopwords, fullStopwordSet, minN)

    const summaryElements = []

    summaryElements.push(<p key="header" style={{margin: 0}}>{`N-GRAM COVERAGE ANALYSIS - ${new Date().toLocaleString()}`}</p>)
    summaryElements.push(<p key="line" style={{margin: 0}}>{`${'='.repeat(60)}`}</p>)
    summaryElements.push(<p key="total" style={{margin: 0}}>{`Total Questions: ${result.totalSentences}`}</p>)
    summaryElements.push(<p key="anchors" style={{margin: 0}}>{`Total Anchors: ${result.anchors.length}`}</p>)
    summaryElements.push(<p key="coverage" style={{margin: 0}}>{`Coverage: ${result.totalCovered}/${result.totalSentences} (${((result.totalCovered / result.totalSentences) * 100).toFixed(1)}%)`}</p>)
    summaryElements.push(<p key="uncovered" style={{margin: 0}}>{`Uncovered: ${result.totalSentences - result.totalCovered}`}</p>)
    summaryElements.push(<p key="blank1" style={{margin: 0}}></p>)

    // Group by length
    const byLength = new Map()
    result.anchors.forEach(anchor => {
      if (!byLength.has(anchor.ngramLength)) {
        byLength.set(anchor.ngramLength, [])
      }
      byLength.get(anchor.ngramLength).push(anchor)
    })

    summaryElements.push(<p key="anchors-header" style={{margin: 0}}>ANCHORS BY LENGTH:</p>)
    summaryElements.push(<p key="blank2" style={{margin: 0}}></p>)

    const sortedLengths = Array.from(byLength.keys()).sort((a, b) => b - a)
    sortedLengths.forEach(length => {
      const anchors = byLength.get(length)
      const totalCoveredByLength = anchors.reduce((sum, anchor) => sum + anchor.sentenceIndices.length, 0)
      summaryElements.push(<p key={`length-${length}`} style={{marginTop: 20}}>{`${length}-word (${totalCoveredByLength} questions):`}</p>)
      anchors.forEach((anchor, i) => {
        summaryElements.push(<p key={`anchor-${length}-${i}`} style={{marginTop: 10}}>{`  ${i+1}. "${anchor.ngram}" (${anchor.sentenceIndices.length} questions)`}</p>)
        summaryElements.push(<p key={`blank-anchor-${length}-${i}`} style={{margin: 0}}></p>)
        anchor.sentenceIndices.forEach(idx => {
          const question = questions[idx]
          const parts = question.split(new RegExp(`(${anchor.ngram})`, 'gi'))
          const highlightedParts = parts.map((part, pidx) => 
            part.toLowerCase() === anchor.ngram.toLowerCase() ? 
              <span key={pidx} className="highlight" style={{backgroundColor: '#ffff00', color: '#000', borderRadius: '3px', padding: '1px'}}>{part}</span> : 
              part
          )
          summaryElements.push(<p key={`question-${length}-${i}-${idx}`} className='question-highlight' style={{ margin: 0, fontSize: 10, color: '#555', marginLeft: 20, marginBottom: 20, marginTop: 5}}>{`${idx}: `}{highlightedParts} <br/>----<br/></p>)
        })
        summaryElements.push(<p key={`blank-after-${length}-${i}`} style={{margin: 0}}></p>)
      })
      summaryElements.push(<p key={`blank-length-${length}`} style={{margin: 0}}></p>)
    })

    if (result.totalCovered < result.totalSentences) {
      summaryElements.push(<p key="uncovered-header" style={{marginTop: 10}}>{`UNCOVERED QUESTIONS: (${result.totalSentences - result.totalCovered} questions)`}</p>)
      const covered = new Set()
      result.anchors.forEach(anchor => {
        anchor.sentenceIndices.forEach(i => covered.add(i))
      })
      for (let i = 0; i < questions.length; i++) {
        if (!covered.has(i)) {
          summaryElements.push(<p key={`uncovered-${i}`} style={{margin: 0, fontSize: 10, color: '#555', marginTop: 5, marginLeft: 20, marginBottom: 20}}>{`${i}: ${questions[i]}`} <br/>----<br/></p>)
        }
      }
    }

    setSummaryJSX(summaryElements)
    setLoading(false)
  }

  return (
    <>
      <Head>
        <title>Extract Terms</title>
        <meta name="description" content="Extract common terms from a list of questions" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <style>{`
      .highlight::selection { background: #ffff00; color: #000; }
      .question-highlight::selection { background: #555; color: #fff; }
      
      `}</style>

      <main className={styles.container}>
        <h1 className={styles.title}>
          Extract Terms
        </h1>
        <span style={{ color: '#777', fontSize: '14px', marginBottom: '20px', display: 'block' }}>Find common phrases in your list of questions</span>


        <textarea
          value={text}
          onChange={(e) => setText(e.target.value)}
          placeholder="Enter your questions, one per line or separated by double lines for multi-line sentences"
          style={{
            width: '100%',
            height: '200px',
            border: '1px solid #333',
            padding: '10px',
            outline: 'none',
            resize: 'vertical'
          }}
        />

        <input
          type="text"
          value={filterWords}
          onChange={(e) => setFilterWords(e.target.value)}
          placeholder="Enter words to filter questions (comma-separated, e.g., budgeting, sheets)"
          style={{
            width: '100%',
            border: '1px solid #333',
            padding: '10px',
            outline: 'none',
            marginTop: '10px'
          }}
        />

        <input
          type="text"
          value={customStopwords}
          onChange={(e) => setCustomStopwords(e.target.value)}
          placeholder="Enter custom stop words to exclude (comma-separated, e.g., please, help)"
          style={{
            width: '100%',
            border: '1px solid #333',
            padding: '10px',
            outline: 'none',
            marginTop: '10px'
          }}
        />

        <div style={{ marginTop: '20px', display: 'flex', flexDirection: 'column', gap: '10px', alignItems: 'flex-start', width: '100%' }}>
          <label>
            Max n-gram length:
          </label>
          <input
              type="number"
              value={maxN}
              onChange={(e) => setMaxN(parseInt(e.target.value) || 1)}
              min="1"
              max="10"
            />
          <label style={{display: 'flex', alignItems: 'center', gap: '5px', width: '100%'}}>
            <input
              type="checkbox"
              style={{width: 10}}
              checked={allowSingleNgram}
              onChange={(e) => setAllowSingleNgram(e.target.checked)}
            />
            Allow single-word n-grams
          </label>
          <label style={{display: 'flex', alignItems: 'center', gap: '5px', width: '100%'}}>
            <input
              type="checkbox"
              style={{width: 10}}
              defaultValue={!removeStopwords}
              onChange={(e) => setRemoveStopwords(e.target.checked)}
            />
            Default stop words
          </label>
          <label style={{display: 'flex', alignItems: 'center', gap: '5px', width: '100%'}}>
            <input
              type="checkbox"
              style={{width: 10}}
              defaultValue={!removeCustomStopwords}
              onChange={(e) => setRemoveCustomStopwords(e.target.checked)}
            />
            Custom stop words
          </label>
          <label>
            Line separator:
            <select
              value={separator}
              onChange={(e) => setSeparator(e.target.value)}
            >
              <option value="single">Single line</option>
              <option value="double">Double line</option>
              <option value="custom">Custom</option>
            </select>
          </label>
          {separator === 'custom' && (
            <input
              type="text"
              value={customSeparator}
              onChange={(e) => setCustomSeparator(e.target.value)}
              placeholder="Enter custom separator, e.g., ; or ---"
              style={{
                width: '100%',
                border: '1px solid #333',
                padding: '10px',
                outline: 'none',
                marginTop: '10px'
              }}
            />
          )}
        </div>

        <button onClick={extractTerms} className={styles.button}>
          {loading ? 'Extracting...' : 'Extract Terms'}
        </button>

        {summaryJSX.length > 0 && (
          <div style={{ whiteSpace: 'pre-wrap', fontFamily: 'monospace', textAlign: 'left', padding: '10px', border: '1px solid #333', borderRadius: 10, background: '#000', width: '100%', lineHeight: 1.5}}>
            {summaryJSX}
          </div>
        )}
      </main>
    </>
  )
}