import Head from 'next/head'
import Image from 'next/image'
import { Inter } from 'next/font/google'
import styles from '@/styles/Home.module.css'
import { useState, useEffect } from 'react'

const inter = Inter({ subsets: ['latin'] })

export default function Home() {

  const tools = [
    {
      title: 'Meta Search',
      description: 'Get boolean search strings for Google, LinkedIn, Github, and more based on the signal you want to find.',
      publishDate: '26th March 2024',
    },
    {
      title: 'Trending tools',
      description: 'Get boolean search strings for Google, LinkedIn, Github, and more based on the signal you want to find.',
      publishDate: '26th March 2024',
    }
  ]
  
  const [search, setSearch] = useState('')
  const [filteredTools, setFilteredTools] = useState(tools)

  useEffect(() => {
    setFilteredTools(tools.filter(tool => tool.title.toLowerCase().includes(search.toLowerCase())))
  }, [search])

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <input className={styles.search} onChange={(e) => {
          setSearch(e.target.value)
        }}>
        </input>
        {filteredTools.map((tool, index) => (
          <div key={index} className={styles.card}>
            <h2>{tool.title}</h2>
            <span className={styles.description}>{tool.description}</span>
            <span className={styles.date}>{tool.publishDate}</span>
          </div>
        ))}
      </main>
    </>
  )
}
