// pick a random winner from the list of participants without gpt api
import Head from "next/head";
import styles from "@/styles/Home.module.css";
import { useState, useEffect } from "react";

export default function RandomWinner() {
  // given a list of participants in a textarea pick a random winner
  const [participants, setParticipants] = useState("");
  const [winner, setWinner] = useState("");

  const pickWinner = () => {
    const participantsList = participants.trim().split("\n");
    const randomIndex = Math.floor(Math.random() * participantsList.length);
    setWinner(participantsList[randomIndex]);
  }

  return (
    <div className={styles.container}>
      <Head>
        <title>Random Winner</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Random Winner
        </h1>

        <p className={styles.description}>
          Pick a random winner from the list of participants
        </p>

        <div style={{
          display: 'flex',
          flexDirection: 'column',
          alignItems: 'center',
          gap: '20px',
        }}>
          <textarea
            value={participants}
            onChange={(e) => setParticipants(e.target.value)}
            placeholder="Enter participants separated by new line"
            className={styles.input}
          />
          <button onClick={pickWinner} className={styles.button}>Pick Winner</button>
          {winner && <div style={{
            fontSize: '24px',
            fontWeight: 'bold',
            padding: '20px',
            borderRadius: '5px',
          }}>{winner}</div>}
        </div>
      </main>
    </div>
  );
}
